---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ${{ values.filename }}
  namespace: secrets
spec:
  data:
  - match:
      remoteRef:
        remoteKey: secret/data/github/repo/${{ values.org }}/${{ values.repoName }}/${{ values.vaultPath }}/credentials
      secretKey: credentials
  deletionPolicy: Delete
  refreshInterval: 1m
  secretStoreRefs:
  - kind: ClusterSecretStore
    name: vault
  selector:
    secret:
      name: ${{ values.source }}
