---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-catalog-root
  description: Root catalog for all entities
spec:
  targets:
    - ./components/*.yaml
    - ./systems/*.yaml
    - ./templates/github/*.yaml
    - ./templates/dockerhub/*.yaml
    - ./templates/secrets/*.yaml
    - https://github.com/rancher-eio/internal-production/blob/main/catalog-info.yaml
