site_name: EIO
site_description: EIO services, and how to get access to them.

nav:
  - Home: index.md
  - Services: services.md
  - Vault secrets: vault-secrets.md
  - How self-service works: how-it-works.md

plugins:
  - techdocs-core
