apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.teamName | dump}}
  #description: ${{values.description | dump}}
  annotations:
    backstage.io/kubernetes-id: app
spec:
  type: team
  lifecycle: experimental
  owner: eio


# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: catalog
# spec:
#   lifecycle: development
#   owner: eio
#   type: service

# Example:
# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: petstore
#   namespace: external-systems
#   description: Petstore
# spec:
#   type: service
#   lifecycle: experimental
#   owner: group:pet-managers
#   providesApis:
#     - petstore
#     - internal/streetlights
#     - hello-world
