apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: team-components
  description: A collection of all team components
spec:
  targets:
    - ./components/poc-team-component.yaml
    - ./components/poc-team-2-component.yaml
    - ./components/poc-team-3-component.yaml
    - ./components/testing-testy-test-team-component.yaml
    - ./components/poc-team-3-component.yaml
    - ./components/poc-team-4-component.yaml
