apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: team-template
  title: GitHub Team Creation Template
  description: Template for creating a GitHub team
spec:
  owner: "eio"
  type: service
  parameters:
    - title: GitHub Team Details
      required:
        - teamName
        - orgName
      properties:
        orgName:
          title: Github Org
          type: string
          description: Name of the GitHub organization
        teamName:
          title: Team Name
          type: string
          description: Name of the GitHub team
<<<<<<< Updated upstream
        # parentTeamId:
        #   title: Parent Team ID
        #   type: number
        #   description: (Optional) ID of the parent GitHub team for nested teams
        # manager:
        #   title: Manager Git Handle
        #   type: string
        #   description: Manager who would approve the request
=======
        parentTeamId:
          title: Parent Team ID
          type: number
          description: (Optional) ID of the parent GitHub team for nested teams
        manager:
          title: Manager Github Name
          type: object
          description: Manager who would approve the request
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: User
          # ui:field: EntityPicker
          # ui:options:
          #   catalogFilter:
          #     kind: Group
          #     'spec.type': team
>>>>>>> Stashed changes
  steps:
    - id: fetch-base
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: https://github.com/rancher-eio/backstage-templates/tree/main/github/test-creation
        targetPath: content
        values:
          teamName: ${{ parameters.teamName }}
          orgName: ${{ parameters.orgName }}

    - id: rename_file
      name: Rename templated file
      action: fs:rename
      input:
        files:
          - from: ./content/skeletons/team-skeleton.yaml
            to: ./content/skeletons/${{ parameters.teamName }}.yaml
