apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: team-template
  title: GitHub Team Creation Template
  description: Template for creating a GitHub team
spec:
  owner: "eio"
  type: service
  parameters:
    - title: GitHub Team Details
      required:
        - teamName
        - orgName
      properties:
        orgName:
          title: Github Org
          type: string
          description: Name of the GitHub organization
        teamName:
          title: Team Name
          type: string
          description: Name of the GitHub team
        parentTeamId:
          title: Parent Team ID
          type: number
          description: (Optional) ID of the parent GitHub team for nested teams
        manager:
          title: Manager Git Handle
          type: string
          description: Manager who would approve the request
  steps:
    - id: fetch-base
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: https://github.com/rancher-eio/backstage-templates/tree/main/github/create-team
        targetPath: content
        values:
          teamName: ${{ parameters.teamName }}
          orgName: ${{ parameters.orgName }}
          parentTeamId: ${{ parameters.parentTeamId }}

    # - id: debug_workspace
    #   name: Debug workspace
    #   action: debug:log
    #   input:
    #     message: "Content of workspace"
    #     listWorkspace: true

    - id: rename_file
      name: Rename templated file
      action: fs:rename
      input:
        files:
          - from: ./content/team-blueprint.yaml
            to: ./content/${{ parameters.teamName }}.yaml

    - id: publish-pr
      name: Publish Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=kitchen&owner=rancher-eio
        title: "Creating team - ${{ parameters.teamName }}"
        description: "This PR creates a new team"
        branchName: "add-new-team-${{ parameters.teamName }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: ${{ parameters.manager }}
        #teamReviewers: "eio"
        commitMessage: "Adding team ${{ parameters.teamName }} to ${{ parameters.orgName }}"
        #sourcePath: ./content
        # targetPath: ./manifests/github-resources/resources/Team/
        files:
          './content/${{ parameters.teamName }}.yaml': 'manifests/github-resources/resources/Team/'
          #'**/*.yaml': 'manifests/github-resources/resources/Team/'

    # - id: write-catalog-info
    #   action: catalog:write
    #   name: Write To Catalog Info
    #   input:
    #     filePath: ./content/catalog-info.yaml
    #     entity:
    #       apiVersion: backstage.io/v1alpha1
    #       kind: Component
    #       metadata:
    #         name: ${{ parameters.teamName }}
    #         description: "GitHub team ${{ parameters.teamName }}"
    #         annotations:
    #           backstage.io/kubernetes-id: app
    #         tags:
    #           - github
    #       spec:
    #         type: service
    #         lifecycle: experimental
    #         owner: eio

    - id: dispatch-workflow
      name: Trigger Workflow
      action: github:actions:dispatch
      input:
        repoUrl: "github.com?repo=backstage-templates&owner=rancher-eio"
        workflowId: "update-team-components.yml"
        branchOrTagName: "main"
        workflowInputs:
          teamName: ${{ parameters.teamName }}
        token: '${{ secrets.GITHUB_TOKEN }}'

    # - id: publish-catalog-info
    #   name: Publish Catalog Info
    #   action: publish:github
    #   input:
    #     repoUrl: github.com?repo=backstage-templates&owner=rancher-eio
    #     branchName: "main"
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     files:
    #       #'./content/catalog-info.yaml': '/github/create-team/components/catalog-info.yaml'
    #       './content/catalog-info.yaml': '/github/create-team/components/${{ parameters.teamName }}-catalog-info.yaml'

    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/rancher-eio/backstage-templates/blob/main/github/create-team/components/${{ parameters.teamName }}-catalog-info.yaml
        # repoContentsUrl: ${{ steps['publish-pr'].output.repoContentsUrl }}
        # catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Pull Request URL
        url: ${{ steps['publish-pr'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
