---
apiVersion: team.github.upbound.io/v1alpha1
kind: TeamMembership
metadata:
  name: ${{ values.resourceName }}
  {%- if values.requestedBy or values.issueNumber %}
  annotations:
    {%- if values.requestedBy %}
    github.eio.rancher.engineering/requested-by: "${{ values.requestedBy }}"
    {%- endif %}
    {%- if values.issueNumber %}
    github.eio.rancher.engineering/issue-number: "${{ values.issueNumber }}"
    {%- endif %}
  {%- endif %}
spec:
  deletionPolicy: Delete
  forProvider:
    role: ${{ values.role }}
    teamId: ${{ values.team }}
    username: ${{ values.username }}
  providerConfigRef:
    name: ${{ values.org }}
