---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eio-docs
  title: EIO
  description: Self-service requests, and how they work.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rancher-eio/backstage-catalog
spec:
  type: documentation
  lifecycle: production
  owner: group:eio
  system: secrets-management
