apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: team-template
  title: GitHub Team Creation Template
  description: Template for creating a GitHub team
spec:
  owner: "eio"
  type: service
  parameters:
    - title: GitHub Team Details
      required:
        - teamName
        - orgName
      properties:
        orgName:
          title: Github Org
          type: string
          description: Name of the GitHub organization
        teamName:
          title: Team Name
          type: string
          description: Name of the GitHub team
        parentTeamId:
          title: Parent Team ID
          type: number
          description: (Optional) ID of the parent GitHub team for nested teams

  steps:
    - id: template
      name: Fill Template
      action: fetch:template
      input:
        url: https://github.com/rancher-eio/backstage-templates/tree/main/blueprints/github
        targetPath: skeleton
        values:
          teamName: ${{ parameters.teamName }}
          orgName: ${{ parameters.orgName }}
          parentTeamId: ${{ parameters.parentTeamId }}
        script:
          - echo "printing template results..."
          - ls ./skeleton
          - echo "done with results"

    - id: rename_file
      name: Rename templated file
      action: fs:rename
      input:
        files:
          - from: ./skeleton/template_blueprint.yaml
            to: ./skeleton/${{ parameters.teamName }}.yaml

    - id: publish-pr
      name: Publish Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=kitchen&owner=rancher-eio
        title: "Add new team"
        description: "This PR adds a new team"
        branchName: "add-new-team-${{ parameters.teamName }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        sourcePath: ./skeleton
        targetPath: ./manifests/github-resources/resources/Team/
        # files:
        #   '**/*.yaml': 'manifests/github-resources/resources/Team/'
