apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: team-template
  title: GitHub Team Creation Template
  description: Template for creating a GitHub team
spec:
  owner: "eio"
  type: service
  parameters:
    - title: GitHub Team Details
      required:
        - teamName
        - orgName
        - manager
      properties:
        orgName:
          title: Github Org
          type: string
          description: Name of the GitHub organization
        teamName:
          title: Team Name
          type: string
          description: Name of the GitHub team
        parentTeamId:
          title: Parent Team ID
          type: number
          description: (Optional) ID of the parent GitHub team for nested teams
        manager:
          title: Manager
          type: string
          description: Manager to approve requests for
  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: https://github.com/rancher-eio/backstage-templates/tree/main/blueprints/github
        targetPath: content
        values:
          teamName: ${{ parameters.teamName }}
          orgName: ${{ parameters.orgName }}
          parentTeamId: ${{ parameters.parentTeamId }}

    - id: rename_file
      name: Rename templated file
      action: fs:rename
      input:
        files:
          - from: ./content/template-blueprint.yaml
            to: ./content/${{ parameters.teamName }}.yaml

    - id: publish-pr
      name: Publish Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=kitchen&owner=rancher-eio
        title: "Creating team - ${{ parameters.teamName }}"
        description: "This PR creates a new team"
        branchName: "add-new-team-${{ parameters.teamName }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: ${{ parameters.manager }}
        teamReviewers: "eio"
        commitMessage: "Adding team ${{ parameters.teamName }} to ${{ parameters.orgName }}"
        sourcePath: ./content
        targetPath: ./manifests/github-resources/resources/Team/
        # files:
        #   '**/*.yaml': 'manifests/github-resources/resources/Team/'
  output:
    links:
      - title: Pull Request URL
        url: ${{ steps['publish-pr'].output.remoteUrl }}
