---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: eio
  title: EIO
  description: EIO services, and how to get access to them.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/rancher-eio/backstage-catalog/tree/main
    github.com/project-slug: rancher-eio/backstage-catalog
    github.com/team-slug: rancher-eio/eio
spec:
  owner: eio
